import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  checkStateManifestV2Compatibility,
  type CompatibilityOutcome,
  type ExpectedStateManifestV2Context,
  type StateManifestV2,
} from './index.js';
import { buildCompatFixtures } from './generate-compat-fixtures.testhelper.js';

const COMPAT_ROOT = path.resolve('protocol/fixtures/state-manifest-v2-compat');

interface CommittedFixture {
  description: string;
  manifest: StateManifestV2;
  expected: ExpectedStateManifestV2Context;
  outcome: CompatibilityOutcome;
}

const NAMES = [
  'compat-continuation',
  'compat-base-change',
  'compat-nondescendant-head',
  'compat-unknown-ancestry',
  'compat-cache-contract-change',
  'compat-state-key-mismatch',
  'compat-contract-version-mismatch',
  'compat-unsafe-provenance',
] as const;

async function readCommitted(name: string): Promise<CommittedFixture> {
  const text = await readFile(path.join(COMPAT_ROOT, `${name}.json`), 'utf8');
  return JSON.parse(text) as CommittedFixture;
}

describe('state-v2 compatibility fixtures (read-only cross-issue oracle)', () => {
  it('directory contains exactly the eight expected fixture files', async () => {
    const entries = await readdir(COMPAT_ROOT);
    expect(entries.sort()).toEqual([...NAMES].map((n) => `${n}.json`).sort());
  });

  for (const name of NAMES) {
    it(`${name}: committed manifest+expected reproduce the committed outcome`, async () => {
      const fx = await readCommitted(name);
      const outcome = checkStateManifestV2Compatibility(fx.manifest, fx.expected);
      expect(outcome).toEqual(fx.outcome);
    });
  }

  it('committed fixture set covers all seven CompatibilityOutcome codes', async () => {
    const seen = new Set<string>();
    for (const name of NAMES) {
      const fx = await readCommitted(name);
      seen.add(
        fx.outcome.kind === 'compatible_continuation'
          ? 'compatible_continuation'
          : `${fx.outcome.kind}:${fx.outcome.code}`,
      );
    }
    expect(seen).toEqual(
      new Set([
        'compatible_continuation',
        'expected_invalidation:base_change',
        'expected_invalidation:head_history_discontinuity',
        'expected_invalidation:cache_contract_change',
        'incompatible:state_key_mismatch',
        'incompatible:contract_version_incompatible',
        'incompatible:unsafe_provenance',
      ]),
    );
  });

  it('regeneration is deterministic (drift guard)', async () => {
    // If the compatibility comparator or its input contract changes, the
    // committed fixtures must be regenerated by a maintainer. This test
    // catches drift by re-computing the outcomes from the in-memory
    // fixture builder and comparing to committed outcomes.
    const built = buildCompatFixtures();
    expect(built.length).toBe(NAMES.length);
    for (const fx of built) {
      const outcome = checkStateManifestV2Compatibility(fx.manifest, fx.expected);
      expect(outcome).toEqual(fx.outcome);
    }
  });
});
