using System.Collections.Immutable;
using System.Text.Json;
using AgenticPrReview.Runtime.Agent;
using AgenticPrReview.Runtime.Agent.Chat;
using AgenticPrReview.Runtime.Agent.Core;
using AgenticPrReview.Runtime.Agent.Loop;
using AgenticPrReview.Runtime.Agent.Session;
using AgenticPrReview.Runtime.Agent.Tools;
using AgenticPrReview.Runtime.Host.State;
using AgenticPrReview.Runtime.ReviewEvaluationFixture.Evaluation;
using AgenticPrReview.Runtime.ReviewEvaluationFixture.Growth.Profiles;
using AgenticPrReview.Runtime.ReviewEvaluationFixture.Replay.Admission;
using AgenticPrReview.Runtime.ReviewEvaluationFixture.Replay.Execution;

namespace AgenticPrReview.Runtime.Tests.Agent.Session;

[Collection(ProcessEnvironmentCollection.Name)]
public sealed class R5SessionGrowthTests
{
    private static string Bundle => Path.Combine(AppContext.BaseDirectory, "fixtures", "agent", "r5", "growth");

    [Fact]
    public void PrivateReplyPreservesAbsenceOfSessionBytes()
    {
        var reply = new ReplayChildReply("op", "corpus", 0, "session", "commit", "tree", false, 1, "startup", "session_failed",
            null, [], null, null, 0, 0, null, [], [], []);
        var bytes = JsonSerializer.SerializeToUtf8Bytes(reply, ReplayExecutionJson.Default.ReplayChildReply);
        var read = ReplayWire.Read(bytes, ReplayExecutionJson.Default.ReplayChildReply, ReplayWire.ReplyLimit);
        Assert.NotNull(read);
        // The generated byte-array writer may encode null as empty base64. Neither is a SESSION artifact.
        Assert.True(read.Plaintext is null or { Length: 0 });
    }

    [Fact]
    public async Task UnknownProfilesAndUnboundedSchedulesRejectBeforeExecution()
    {
        foreach (var options in new[] { new GrowthOptions { Profile = "unknown" }, new GrowthOptions { AttemptLimit = GrowthProfiles.Attempts + 1 },
            new GrowthOptions { AttemptLimit = 0 } })
        {
            var report = await GrowthRunner.RunAsync(Bundle, options);
            Assert.Equal("input_invalid", report.Code);
            Assert.Empty(report.Profiles);
        }
        Assert.False(GrowthProfiles.ValidPhase("short", GrowthProfiles.Attempts));
        Assert.False(GrowthProfiles.ValidPhase("short", -1));
        Assert.False(GrowthProfiles.ValidPhase("unknown", 0));
        Assert.True(GrowthProfiles.ValidPhase("short", GrowthProfiles.Attempts - 1));
        var fixture = ReplayAdmission.Load(Bundle).Fixture!;
        Assert.True(GrowthProfiles.Matches(fixture));
        Assert.False(GrowthProfiles.Matches(new(fixture.CorpusSha256, fixture.Files, fixture.Runs.RemoveAt(0))));
    }

    [Theory]
    [InlineData((int)ReplayFault.GrowthModelBudget, "run_budget", AgentFailureCodes.ModelLimit)]
    [InlineData((int)ReplayFault.WrongScope, "invalid_current_state", RestrictedStateCodes.EnvelopeInvalid)]
    [InlineData((int)ReplayFault.WrongReply, "harness_failure", "result_invalid")]
    public async Task FailureControlsPreserveTheAcceptedPredecessor(int faultValue, string classification, string expectedCode)
    {
        var fault = (ReplayFault)faultValue;
        var report = await GrowthRunner.RunAsync(Bundle, new() { Profile = "short", Fault = fault });
        var profile = Assert.Single(report.Profiles);
        Assert.Equal(2, profile.Rows.Length);
        var failed = profile.Rows[^1];
        Assert.False(failed.Accepted);
        Assert.Null(failed.State);
        Assert.True(failed.PredecessorPreserved);
        Assert.Equal(profile.Rows[0].State, failed.Before);
        Assert.Equal(classification, failed.Classification);
        Assert.Equal(expectedCode, failed.Code);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
        Assert.Equal(fault, report.Schedule.Fault);
        Assert.NotEqual(GrowthProfiles.Corpus(ReplayAdmission.Load(Bundle).Fixture!), report.CorpusSha256);
    }

    [Fact]
    public async Task FiniteExhaustionAndReportMutationsDoNotInventCapacityEvidence()
    {
        var report = await GrowthRunner.RunAsync(Bundle, new() { Profile = "short", AttemptLimit = 1 });
        var profile = Assert.Single(report.Profiles);
        Assert.Equal("observation_incomplete", report.Code);
        Assert.False(profile.LimitObserved);
        Assert.Equal("attempt_limit", profile.TerminalCode);
        var row = Assert.Single(profile.Rows);
        Assert.True(row.Accepted);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
        var state = row.State!;
        foreach (var changed in new[] { state with { Records = -1 }, state with { ScopeBytes = state.ScopeBytes + 1 },
            state with { CompletedRuns = state.CompletedRuns + 1 }, state with { PredecessorEnvelopeSha256 = new string('f', 64) } })
        {
            var profiles = report.Profiles.SetItem(0, profile with { Rows = [row with { State = changed }] });
            var altered = report with { Profiles = profiles, NormalizedSha256 = GrowthJson.Normalize(profiles) };
            Assert.Null(GrowthJson.Read(GrowthJson.Write(altered)));
        }
        Assert.Null(GrowthJson.Read(GrowthJson.Write(report with { Profiles = [profile with { LimitObserved = true }] })));
        Assert.Null(GrowthJson.Read(GrowthJson.Write(report with { Schedule = report.Schedule with { AttemptLimit = 2 } })));
        var text = System.Text.Encoding.UTF8.GetString(GrowthJson.Write(report));
        Assert.Null(GrowthJson.Read(System.Text.Encoding.UTF8.GetBytes("{\"unexpected\":1," + text[1..])));
    }

    [Fact]
    public async Task RehashedAlteredPriorContentCannotReplaceThePreparedState()
    {
        var altered = false;
        var report = await GrowthRunner.RunAsync(Bundle, new()
        {
            Profile = "short", AttemptLimit = 2,
            TransformReply = (input, reply) =>
            {
                if (input.Phase == 0 || reply.Plaintext is null || reply.Prepared is null) return reply;
                if (!AgentSessionCodec.TryParse(reply.Plaintext, out var artifact, out _)) return reply;
                var first = artifact!.Document.CompletedRuns[0];
                var context = (AgentSessionReviewContextRecord)first.Records[0];
                var changed = first with { Records = first.Records.SetItem(0, context with { Text = "Altered predecessor." }) };
                if (!AgentSessionCodec.TryWrite(artifact.Document with { CompletedRuns = artifact.Document.CompletedRuns.SetItem(0, changed) }, out var rewritten, out _)) return reply;
                var fixture = ReplayAdmission.Load(Bundle).Fixture!;
                var run = GrowthProfiles.Run(fixture, "short", input.Phase, input.Fault, input.GrowthSchedule);
                altered = true;
                return reply with { Plaintext = rewritten!.Plaintext,
                    LogicalSha256 = ReplayProjection.Logical(rewritten, run.CreateTrustedRequest(ReplayState.Build)),
                    Prepared = reply.Prepared with { SessionSha256 = rewritten.SessionSha256 } };
            },
        });
        Assert.True(altered);
        var last = Assert.Single(report.Profiles).Rows[^1];
        Assert.False(last.Accepted);
        Assert.True(last.PredecessorPreserved);
        Assert.NotEqual("append_limit", last.Classification);
        Assert.Equal("observation_incomplete", report.Code);
        Assert.Equal("accept", last.Stage);
        Assert.Equal(EvaluationStatus.Completed, report.Profiles[0].Evaluation.Outcomes.Single(o => o.CaseId == last.CaseId).ExecutionStatus);
        Assert.Equal(2, report.Profiles[0].Evaluation.Summary.Execution.Completed);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
    }

    [Fact]
    public async Task DiagnosticForgeryAndCleanupFailureStayFailures()
    {
        var forged = await GrowthRunner.RunAsync(Bundle, new()
        {
            Profile = "short", AttemptLimit = 2,
            TransformReply = (input, reply) => input.Phase == 0 ? reply : reply with
            { ObservedStage = "build", ObservedCode = AgentSessionCodes.ConstructionLimit },
        });
        var row = Assert.Single(forged.Profiles).Rows[^1];
        Assert.Equal("result_invalid", row.Code);
        Assert.True(row.PredecessorPreserved);
        var cleanup = await GrowthRunner.RunAsync(Bundle, new()
        {
            Profile = "short", AttemptLimit = 1, Cleanup = root => { Assert.True(ReplayProcess.Cleanup(root)); return false; },
        });
        Assert.Equal("cleanup_failed", cleanup.Code);
        Assert.NotEqual(0, cleanup.ExitCode);
    }

    [Fact]
    public async Task MatrixMeasuresActualArtifactsAndReproducesFirstBoundary()
    {
        var observed = new Dictionary<string, List<(int Bytes, int Entries, long Continuation)>>();
        var startups = new HashSet<string>();
        var diagnostics = new List<string>();
        var report = await GrowthRunner.RunAsync(Bundle, new()
        {
            TransformReply = (input, reply) =>
            {
                var fixture = ReplayAdmission.Load(Bundle).Fixture!;
                var run = GrowthProfiles.Run(fixture, input.GrowthProfile!, input.Phase);
                var okay = ReplayRunner.AdmitReply(input, run, reply, out var outcome);
                if (!okay) diagnostics.Add($"{reply.Code}/{reply.ObservedStage}/{reply.ObservedCode}; evaluation={outcome?.ExecutionStatus}; diagnostic={GrowthProfiles.Diagnostic(reply, outcome)}; identity={ReplayRunner.AdmitIdentity(input, reply)}; model={reply.ModelCalls}; requests={reply.Requests.Length}; counts={reply.GrowthCounts}; plaintext={reply.Plaintext is null}/{reply.Plaintext?.Length}; receipt={reply.Prepared is null}");
                return reply;
            },
            ObserveReply = (input, reply) =>
            {
                Assert.True(startups.Add(reply.Startup));
                if (reply.Plaintext is null or { Length: 0 }) { Assert.Null(reply.Prepared); return; }
                Assert.True(AgentSessionCodec.TryParse(reply.Plaintext, out var artifact, out _));
                if (!observed.TryGetValue(input.GrowthProfile!, out var list)) observed.Add(input.GrowthProfile!, list = []);
                list.Add((reply.Plaintext.Length, artifact!.Document.CompletedRuns.Sum(r => r.Records.Length + r.Continuation.Items.Length),
                    artifact.Document.CompletedRuns.Sum(r => r.Continuation.Items.Sum(i => (long)i.PayloadBytes.Length))));
            },
        });
        Assert.True(report.Code == "verified", report.Code + ": " + string.Join("; ", diagnostics));
        Assert.Equal("cleaned", report.Cleanup);
        Assert.Equal(GrowthProfiles.Names, report.Profiles.Select(p => p.Profile));
        Assert.Equal(AgentSessionCodes.ConstructionLimit, report.Profiles[0].TerminalCode);
        Assert.Equal("message_limit", report.Profiles[1].Rows[^1].Classification);
        Assert.Equal("continuation_limit", report.Profiles[2].Rows[^1].Classification);
        Assert.Equal("message_limit", report.Profiles[3].Rows[^1].Classification);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
        foreach (var profile in report.Profiles)
        {
            Assert.True(profile.LimitObserved);
            Assert.InRange(profile.Rows.Length, 2, GrowthProfiles.Attempts);
            Assert.All(profile.Rows, row => Assert.True(row.PredecessorPreserved));
            Assert.False(profile.Rows[^1].Accepted);
            Assert.Null(profile.Rows[^1].State);
            Assert.NotNull(profile.Rows[^1].Before);
            Assert.Equal(profile.Rows.Length, profile.Evaluation.Outcomes.Length);
            var accepted = profile.Rows.Where(r => r.Accepted).ToArray();
            Assert.Equal(observed[profile.Profile].Count, accepted.Length);
            for (var index = 0; index < accepted.Length; index++)
            {
                var state = accepted[index].State!;
                Assert.Equal(index, state.Generation);
                Assert.Equal(observed[profile.Profile][index], (state.PlaintextBytes, state.Records, state.ContinuationBytes));
            }
        }
        var again = await GrowthRunner.RunAsync(Bundle);
        Assert.Equal("verified", again.Code);
        Assert.Equal(report.NormalizedSha256, again.NormalizedSha256);
        Assert.Equal(report.Profiles.Select(p => (p.TerminalStage, p.TerminalCode, p.Rows.Length)),
            again.Profiles.Select(p => (p.TerminalStage, p.TerminalCode, p.Rows.Length)));
        var text = System.Text.Encoding.UTF8.GetString(GrowthJson.Write(report));
        foreach (var secret in new[] { "Synthetic growth fixture.", "Synthetic complete.", "synthetic-continuation-", "reasoning_content", "\"tool_calls\":[", "exception" })
            Assert.DoesNotContain(secret, text);
    }

    [Fact]
    public async Task AmbientCanaryDoesNotEnterTheChildOrPublicReport()
    {
        const string name = "R5_GROWTH_TEST_TOKEN";
        var previous = Environment.GetEnvironmentVariable(name);
        var canary = "synthetic-private-" + Guid.NewGuid().ToString("N");
        try
        {
            Environment.SetEnvironmentVariable(name, canary);
            var childClean = false;
            var report = await GrowthRunner.RunAsync(Bundle, new()
            {
                Profile = "short", AttemptLimit = 1, ObserveReply = (_, reply) =>
                    childClean = !reply.EnvironmentKeys.Contains(name) && !System.Text.Encoding.UTF8.GetString(reply.EnvironmentBytes).Contains(canary, StringComparison.Ordinal),
            });
            Assert.True(childClean);
            Assert.DoesNotContain(canary, System.Text.Encoding.UTF8.GetString(GrowthJson.Write(report)));
        }
        finally { Environment.SetEnvironmentVariable(name, previous); }
    }

    [Theory]
    [InlineData(false)] [InlineData(true)]
    public async Task PostReplyFailureRetainsTheAttemptAndConfirmedPrefix(bool cancel)
    {
        using var cancellation = new CancellationTokenSource();
        var report = await GrowthRunner.RunAsync(Bundle, new()
        {
            Profile = "short", ObserveReply = (input, _) =>
            {
                if (input.Phase != 1) return;
                if (cancel) cancellation.Cancel();
                else throw new InvalidOperationException("private-test-exception-not-output");
            },
        }, cancellation.Token);
        var profile = Assert.Single(report.Profiles);
        Assert.Equal(2, profile.Rows.Length);
        Assert.True(profile.Rows[0].Accepted);
        Assert.False(profile.Rows[1].Accepted);
        Assert.True(profile.Rows[1].PredecessorPreserved);
        Assert.Equal(cancel ? "cancelled" : "infrastructure_failed", profile.TerminalCode);
        Assert.Null(profile.Rows[1].ProviderRequestBytes);
        var bytes = GrowthJson.Write(report);
        Assert.NotNull(GrowthJson.Read(bytes));
        Assert.DoesNotContain("private-test-exception-not-output", System.Text.Encoding.UTF8.GetString(bytes));
    }

    [Theory]
    [InlineData(0)] [InlineData(1)]
    public async Task ZeroCallCancellationRetainsActualAgentDiagnostic(int phase)
    {
        var report = await GrowthRunner.RunAsync(Bundle, new() { Profile = "short", Fault = ReplayFault.Cancelled, FaultPhase = phase });
        var profile = Assert.Single(report.Profiles);
        Assert.Equal(phase + 1, profile.Rows.Length);
        var row = profile.Rows[^1];
        Assert.Equal("agent", row.Stage);
        Assert.Equal(AgentFailureCodes.Cancelled, row.Code);
        Assert.False(row.Accepted);
        Assert.True(row.PredecessorPreserved);
        Assert.Equal(0, row.ModelCalls);
        Assert.Equal(0, row.ToolCalls);
        Assert.Equal(0, row.ProviderRequests);
        Assert.Equal(0, row.ProviderRequestBytes);
        Assert.Null(row.LastProviderRequestBytes);
        Assert.Null(row.Project);
        Assert.Equal(EvaluationStatus.Failed, profile.Evaluation.Outcomes.Single(o => o.CaseId == row.CaseId).ExecutionStatus);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
    }

    [Theory]
    [InlineData("build", AgentSessionCodes.ConstructionLimit, "append_limit")]
    [InlineData("agent", AgentFailureCodes.ModelLimit, "run_budget")]
    [InlineData("executor", "result_invalid", "harness_failure")]
    public async Task RehashedFailureCannotKeepCompletedQ1Outcome(string stage, string code, string classification)
    {
        var report = await GrowthRunner.RunAsync(Bundle, new() { Profile = "short", AttemptLimit = 1 });
        var profile = Assert.Single(report.Profiles);
        var row = Assert.Single(profile.Rows) with { Accepted = false, State = null, Stage = stage, Code = code, Classification = classification };
        var limit = classification != "harness_failure";
        var profiles = ImmutableArray.Create(profile with { Rows = [row], TerminalStage = stage, TerminalCode = code, LimitObserved = limit });
        var changed = report with { Code = limit ? "verified" : "observation_incomplete", Profiles = profiles, NormalizedSha256 = GrowthJson.Normalize(profiles) };
        Assert.Null(GrowthJson.Read(GrowthJson.Write(changed)));
    }

    [Fact]
    public async Task UnreapedDispositionRetainsPrefixWithoutReadbackOrCleanup()
    {
        string? retained = null;
        var cleanupCalled = false;
        try
        {
            var report = await GrowthRunner.RunAsync(Bundle, new()
            {
                Profile = "short", AttemptLimit = 2,
                RunProcess = (input, timeout, token) =>
                {
                    retained = input.Root;
                    // Typed supervisor-failure witness; no live OS process is left running by this test.
                    return input.Phase == 0 ? ReplayProcess.RunAsync(input, timeout, token) : throw new ReplayProcessUnreaped();
                },
                Cleanup = root => { cleanupCalled = true; return ReplayProcess.Cleanup(root); },
            });
            var profile = Assert.Single(report.Profiles);
            Assert.Equal(2, profile.Rows.Length);
            Assert.True(profile.Rows[0].Accepted);
            var failed = profile.Rows[1];
            Assert.False(failed.Accepted);
            Assert.False(failed.PredecessorPreserved);
            Assert.Equal(profile.Rows[0].State, failed.Before);
            Assert.Null(failed.State);
            Assert.Null(failed.ProviderRequestBytes);
            Assert.Equal("process_unreaped", failed.Code);
            Assert.Equal("cleanup_failed", report.Cleanup);
            Assert.False(cleanupCalled);
            Assert.True(Directory.Exists(retained));
            Assert.Equal(2, profile.Evaluation.Outcomes.Length);
            Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
            Assert.Null(GrowthJson.Read(GrowthJson.Write(report with { Code = "observation_incomplete", Cleanup = "cleaned" })));
        }
        finally { if (retained is not null) Assert.True(ReplayProcess.Cleanup(retained)); }
    }

    [Fact]
    public async Task ThrowingCleanupCannotClaimArtifactsWereRemoved()
    {
        string? retained = null;
        try
        {
            var report = await GrowthRunner.RunAsync(Bundle, new()
            {
                Profile = "short", AttemptLimit = 1,
                Cleanup = root => { retained = root; throw new IOException("synthetic-cleanup-failure"); },
            });
            Assert.Equal("cleanup_failed", report.Cleanup);
            Assert.Equal("cleanup_failed", report.Code);
            Assert.True(Assert.Single(Assert.Single(report.Profiles).Rows).Accepted);
            Assert.True(Directory.Exists(retained));
            var bytes = GrowthJson.Write(report);
            Assert.NotNull(GrowthJson.Read(bytes));
            Assert.DoesNotContain("synthetic-cleanup-failure", System.Text.Encoding.UTF8.GetString(bytes));
        }
        finally { if (retained is not null) Assert.True(ReplayProcess.Cleanup(retained)); }
    }

    [Theory]
    [InlineData("diagnostic")] [InlineData("provider_digest")] [InlineData("startup")]
    public async Task RejectedRepliesCannotContributeQ1Quality(string mutation)
    {
        string? startup = null;
        var report = await GrowthRunner.RunAsync(Bundle, new()
        {
            Profile = "short", AttemptLimit = 2,
            TransformReply = (input, reply) =>
            {
                if (input.Phase == 0) { startup = reply.Startup; return reply; }
                return mutation switch
                {
                    "diagnostic" => reply with { ObservedStage = "build", ObservedCode = AgentSessionCodes.ConstructionLimit },
                    "provider_digest" => reply with { ProviderSha256 = new string('f', 64) },
                    _ => reply with { Startup = startup! },
                };
            },
        });
        var profile = Assert.Single(report.Profiles);
        var last = profile.Rows[^1];
        Assert.Equal("result_invalid", last.Code);
        Assert.False(last.Accepted);
        Assert.True(last.PredecessorPreserved);
        var outcome = profile.Evaluation.Outcomes.Single(o => o.CaseId == last.CaseId);
        Assert.Equal(EvaluationStatus.Invalid, outcome.ExecutionStatus);
        Assert.Equal(EvaluationFailureSource.Evaluator, outcome.FailureSource);
        Assert.Null(outcome.ExecutionSha256);
        Assert.Equal(AssertionStatus.NotEvaluated, outcome.EvidenceStatus);
        Assert.Equal(AssertionStatus.NotEvaluated, outcome.ScenarioStatus);
        Assert.Equal(ModelObservationStatus.NotEvaluated, outcome.ModelStatus);
        Assert.Equal(1, profile.Evaluation.Summary.Execution.Completed);
        Assert.Equal(1, profile.Evaluation.Summary.Execution.Invalid);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
    }

    [Theory]
    [InlineData(1, "cancelled")] [InlineData(2, "cancelled")]
    [InlineData(1, "io")] [InlineData(2, "io")]
    [InlineData(1, "content")] [InlineData(2, "content")]
    public async Task TypedAdmissionResultsRetainOperationalAttribution(int call, string failure)
    {
        var calls = 0;
        var cleanupCalled = false;
        var report = await GrowthRunner.RunAsync(Bundle, new()
        {
            Profile = "short", AttemptLimit = 1,
            AdmitBundle = (path, token) =>
            {
                if (++calls != call) return ReplayAdmission.Load(path, token);
                if (failure == "cancelled")
                {
                    var cancelled = ReplayAdmission.Load(path, new CancellationToken(true));
                    Assert.Equal(ReplayAdmissionCode.Cancelled, cancelled.Code);
                    return cancelled;
                }
                return new(failure == "io" ? ReplayAdmissionCode.IoFailure : ReplayAdmissionCode.ContentMismatch, null);
            },
            Cleanup = root => { cleanupCalled = true; return ReplayProcess.Cleanup(root); },
        });
        Assert.Equal(failure switch { "cancelled" => "cancelled", "io" => "infrastructure_failed", _ => "input_invalid" }, report.Code);
        Assert.Equal(call == 2, cleanupCalled);
        Assert.Equal("cleaned", report.Cleanup);
        Assert.Empty(report.Profiles);
        Assert.NotNull(GrowthJson.Read(GrowthJson.Write(report)));
    }
}

public sealed partial class AgentSessionRoundTripTests
{
    [Theory]
    [InlineData(-1)] [InlineData(0)] [InlineData(1)]
    public async Task R5GrowthCumulativeRecordAdmissionBoundary(int delta)
    {
        var trusted = Trusted();
        BuiltGeneration? previous = null;
        for (var index = 0; index < 19; index++)
            previous = await BuildGenerationWithContinuationCountAsync(trusted, previous, "prior-" + index, "finish" + index, index < 6 ? 11 : 10);
        var document = AddTerminalContinuationItems(previous!.Artifact.Document, 3 + delta);
        Assert.Equal(AgentLimits.SessionRecords + delta, document.CompletedRuns.Sum(r => r.Records.Length + r.Continuation.Items.Length));
        Assert.Equal(delta <= 0, AgentSessionValidation.TryValidateRecords(document, SyntheticContinuationCodec.Instance, out _));
    }

    [Theory]
    [InlineData(-1)] [InlineData(0)] [InlineData(1)]
    public async Task R5GrowthRootCountBoundaryIsNotAcceptedHistory(int delta)
    {
        var built = await BuildGenerationAsync(Trusted(), null, "g0", "finish0", reasoning: false);
        var count = AgentSessionFormat.MaximumCompletedRuns + delta;
        var run = built.Artifact.Document.CompletedRuns[0];
        var document = built.Artifact.Document with
        {
            Generation = count - 1, PriorSessionSha256 = new string('a', 64), PredecessorStateSha256 = new string('b', 64),
            CompletedRuns = Enumerable.Range(0, count).Select(i => run with { RunId = "root-" + i, RunOrdinal = i }).ToImmutableArray(),
        };
        document = document with { CompletedRuns = document.CompletedRuns.SetItem(count - 1, document.CompletedRuns[^1] with
            { StablePlanSha256 = AgentCanonical.StablePlanSha256(AgentSessionValidation.PlanFromRoot(document, document.PriorSessionSha256)) }) };
        Assert.Equal(delta <= 0, AgentSessionValidation.TryValidateRoot(document, out _));
        // This is root grammar only. Shared record IDs/history are intentionally not completed replay evidence.
        Assert.False(AgentSessionValidation.TryValidateRecords(document, SyntheticContinuationCodec.Instance, out _));
    }

    [Theory]
    [InlineData(-1)] [InlineData(0)] [InlineData(1)]
    public async Task R5GrowthPlaintextAndRecordWriterBoundaries(int delta)
    {
        var built = await BuildGenerationAsync(Trusted(), null, "g0", "finish0", reasoning: false);
        var context = (AgentSessionReviewContextRecord)built.Artifact.Document.CompletedRuns[0].Records[0];
        var empty = context with { Text = "" };
        var record = empty with { Text = new string('x', AgentLimits.SessionRecordBytes - AgentSessionCodec.WriteRecordBytes(empty).Length + delta) };
        var bytes = AgentSessionCodec.WriteRecordBytes(record);
        if (delta > 0) Assert.Empty(bytes); else Assert.Equal(AgentLimits.SessionRecordBytes + delta, bytes.Length);
        var root = built.Artifact.Document with { WorkflowIdentity = "" };
        Assert.True(AgentSessionCodec.TryWrite(root, out var baseline, out _));
        root = root with { WorkflowIdentity = new string('w', AgentLimits.SessionPlaintextBytes - baseline!.Plaintext.Length + delta) };
        Assert.Equal(delta <= 0, AgentSessionCodec.TryWrite(root, out var artifact, out var code));
        if (delta > 0) { Assert.Null(artifact); Assert.Equal(AgentSessionCodes.ConstructionLimit, code); }
        else Assert.Equal(AgentLimits.SessionPlaintextBytes + delta, artifact!.Plaintext.Length);
        Assert.False(AgentSessionValidation.TryValidateRoot(root, out _));
    }

    [Theory]
    [InlineData(-1)] [InlineData(0)] [InlineData(1)]
    public async Task R5GrowthDecodedContinuationBoundaries(int delta)
    {
        var single = await BuildSizedContinuationAsync([AgentLimits.ContinuationItemBytes + delta]);
        Assert.Equal(delta <= 0, single.Succeeded);
        var total = AgentLimits.ContinuationTotalBytes + delta;
        var lengths = Enumerable.Repeat(total / 5, 5).ToArray();
        lengths[^1] += total % 5;
        var aggregate = await BuildSizedContinuationAsync(lengths);
        Assert.Equal(delta <= 0, aggregate.Succeeded);
        if (delta > 0)
        {
            Assert.Null(single.Artifact); Assert.Null(aggregate.Artifact);
            Assert.Equal(AgentSessionCodes.ConstructionLimit, single.FailureCode);
            Assert.Equal(AgentSessionCodes.ConstructionLimit, aggregate.FailureCode);
        }
    }

    [Theory]
    [InlineData(-1)] [InlineData(0)] [InlineData(1)]
    public void R5GrowthReconstructedRequestByteAndMessageBoundaries(int delta)
    {
        var trusted = Trusted();
        var messages = Enumerable.Range(0, 16).Select(_ => User(new string('x', AgentLimits.ContentBytes - 4096))).ToArray();
        int Size() => AgentRequestWriter.Write(new(messages, AgentToolRegistry.Definitions.ToArray(), Continuation: null, ThinkingRequired: true)).Length;
        var remaining = AgentLimits.RequestBytes + delta - Size();
        for (var index = 0; index < messages.Length && remaining > 0; index++)
        {
            var add = Math.Min(remaining, 4096);
            messages[index] = User(new string('x', AgentLimits.ContentBytes - 4096 + add));
            remaining -= add;
        }
        Assert.Equal(0, remaining);
        Assert.Equal(AgentLimits.RequestBytes + delta, Size());
        var request = new AgentRunRequest(Identity(), Materialize(trusted, null), "session0", messages);
        Assert.Equal(delta <= 0, AgentSessionRestorer.TryValidateReconstructedRequest(request));
        var messageBound = request with { InitialMessages = Enumerable.Range(0, AgentLimits.Messages + delta).Select(_ => User("x")).ToArray() };
        Assert.Equal(delta <= 0, AgentSessionRestorer.TryValidateReconstructedRequest(messageBound));
    }
}
