<Project>
  <PropertyGroup>
    <AiAbstractionCandidatePath Condition="'$(AiAbstractionCandidate)' == 'MicrosoftExtensionsAI'">MicrosoftExtensionsAI</AiAbstractionCandidatePath>
    <AiAbstractionCandidatePath Condition="'$(AiAbstractionCandidate)' == 'Minimal'">Minimal</AiAbstractionCandidatePath>
    <AiAbstractionCandidatePath Condition="'$(AiAbstractionCandidatePath)' == ''">invalid</AiAbstractionCandidatePath>
    <AiAbstractionMode Condition="'$(AiAbstractionMode)' == ''">manual</AiAbstractionMode>
    <AiAbstractionIsolationRoot Condition="'$(AiAbstractionIsolationRoot)' == ''">$(MSBuildThisFileDirectory)obj/isolated/$(AiAbstractionCandidatePath)/$(AiAbstractionMode)/</AiAbstractionIsolationRoot>
    <MSBuildProjectExtensionsPath Condition="'$(MSBuildProjectExtensionsPath)' == ''">$(AiAbstractionIsolationRoot)extensions/</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">$(AiAbstractionIsolationRoot)intermediate/</BaseIntermediateOutputPath>
    <BaseOutputPath Condition="'$(BaseOutputPath)' == ''">$(MSBuildThisFileDirectory)bin/isolated/$(AiAbstractionCandidatePath)/$(AiAbstractionMode)/</BaseOutputPath>
    <RestorePackagesPath Condition="'$(RestorePackagesPath)' == ''">$(AiAbstractionIsolationRoot)packages/</RestorePackagesPath>
  </PropertyGroup>
</Project>
