import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

export const ACTION_BUNDLE_RELATIVE_PATH = '.github/actions/agentic-pr-review/dist/index.js';
export const WRAPPER_BUILD_DISCRIMINATOR = 'r4-w2';

const scriptPath = fileURLToPath(import.meta.url);
const defaultRepoRoot = path.resolve(path.dirname(scriptPath), '..');
const virtualEntryPoint = 'scripts/action-entrypoint.generated.ts';
const optionalDebugColorStubSource = 'module.exports = false;\n';
const optionalDebugColorStub = {
  name: 'optional-debug-color-stub',
  setup(buildContext) {
    buildContext.onResolve({ filter: /^supports-color$/ }, () => ({
      namespace: 'action-build-stub',
      path: 'supports-color',
    }));
    buildContext.onLoad({ filter: /^supports-color$/, namespace: 'action-build-stub' }, () => ({
      contents: optionalDebugColorStubSource,
      loader: 'js',
    }));
  },
};
const entryPointSource = `
import { runPrivateActionWrapper } from '../src/action-wrapper/index.js';

const WRAPPER_BUILD_DISCRIMINATOR = ${JSON.stringify(WRAPPER_BUILD_DISCRIMINATOR)};

void runPrivateActionWrapper({
  trustedRoot: process.env.AGENTIC_PR_REVIEW_PREPARED_ROOT,
  executableRelativePath: process.env.AGENTIC_PR_REVIEW_PREPARED_EXECUTABLE,
  payloadSha256: process.env.AGENTIC_PR_REVIEW_PREPARED_PAYLOAD_SHA256,
  actionSourceSha: process.env.AGENTIC_PR_REVIEW_ACTION_SOURCE_SHA,
  buildDiscriminator: process.env.AGENTIC_PR_REVIEW_PAYLOAD_BUILD_DISCRIMINATOR,
  wrapperBuildDiscriminator: WRAPPER_BUILD_DISCRIMINATOR,
}).then(
  (exitCode) => {
    process.exitCode = exitCode;
  },
  () => {
    process.exitCode = 1;
  },
);
`;

export async function generateActionBundle(repoRoot = defaultRepoRoot) {
  const result = await build({
    absWorkingDir: path.resolve(repoRoot),
    banner: {
      js: [
        '// Generated by npm run build:action. Do not edit.',
        "import { createRequire as __actionCreateRequire } from 'node:module';",
        'const require = __actionCreateRequire(import.meta.url);',
      ].join('\n'),
    },
    bundle: true,
    charset: 'utf8',
    format: 'esm',
    legalComments: 'none',
    logLevel: 'silent',
    metafile: true,
    outfile: ACTION_BUNDLE_RELATIVE_PATH,
    packages: 'bundle',
    platform: 'node',
    plugins: [optionalDebugColorStub],
    preserveSymlinks: true,
    sourcemap: false,
    stdin: {
      contents: entryPointSource,
      loader: 'ts',
      resolveDir: path.join(path.resolve(repoRoot), 'scripts'),
      sourcefile: path.basename(virtualEntryPoint),
    },
    target: ['node24'],
    treeShaking: true,
    write: false,
  });
  if (result.outputFiles.length !== 1 || !result.metafile) {
    throw new Error('action_bundle_generation_invalid');
  }
  const sourceDigest = await actionSourceDigest(repoRoot, result.metafile);
  return {
    bytes: Buffer.concat([
      Buffer.from(result.outputFiles[0].contents),
      Buffer.from(`// Action source inventory sha256: ${sourceDigest}\n`, 'utf8'),
    ]),
    metafile: result.metafile,
  };
}

export async function actionSourceDigest(repoRoot, metafile) {
  const sources = new Map([
    ['scripts/action-entrypoint.generated.ts', Buffer.from(entryPointSource, 'utf8')],
    ['action-build-stub:supports-color', Buffer.from(optionalDebugColorStubSource, 'utf8')],
    ['scripts/build-action.mjs', await readFile(path.join(repoRoot, 'scripts/build-action.mjs'))],
  ]);
  for (const source of Object.keys(metafile.inputs)) {
    if (sources.has(source)) continue;
    sources.set(source, await readFile(path.join(repoRoot, source)));
  }
  const digest = createHash('sha256');
  for (const [source, bytes] of [...sources].sort(([left], [right]) => left.localeCompare(right))) {
    const name = Buffer.from(source, 'utf8');
    const boundary = Buffer.allocUnsafe(8);
    boundary.writeUInt32BE(name.byteLength, 0);
    boundary.writeUInt32BE(bytes.byteLength, 4);
    digest.update(boundary);
    digest.update(name);
    digest.update(bytes);
  }
  return digest.digest('hex');
}

export async function writeActionBundle(repoRoot = defaultRepoRoot) {
  const root = path.resolve(repoRoot);
  const outputPath = path.join(root, ACTION_BUNDLE_RELATIVE_PATH);
  const temporaryPath = `${outputPath}.tmp-${process.pid}-${randomUUID()}`;
  const generated = await generateActionBundle(root);
  await mkdir(path.dirname(outputPath), { recursive: true });
  try {
    await writeFile(temporaryPath, generated.bytes, { flag: 'wx' });
    try {
      await rename(temporaryPath, outputPath);
    } catch (error) {
      if (error?.code !== 'EEXIST' && error?.code !== 'EPERM') throw error;
      await rm(outputPath, { force: true });
      await rename(temporaryPath, outputPath);
    }
  } finally {
    await rm(temporaryPath, { force: true });
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === scriptPath) {
  await writeActionBundle();
}
